### ISSUE TITLE
Spelling mistake in py-music-bot/Pipfile

### ISSUE THREAD

**Issue by bypequeno** [joek13/py-music-bot#15]
youtube-dl shoul be called youtube_dl

**Comment by joek13** [comment]
It looks like [youtube-dl](https://pypi.org/project/youtube-dl/) just redirects to [youtube_dl](https://pypi.org/project/youtube_dl/) on PyPI. Moreover, the [Installation](https://github.com/ytdl-org/youtube-dl#installation) section in README suggests you use `sudo -H pip install --upgrade youtube-dl`. This isn't an issue.
