### ISSUE TITLE
Add on_message event

### ISSUE THREAD

**Issue by sistematico** [joek13/py-music-bot#16]
I'm trying to do this:

musicbot/cogs/reply.py
```python
import discord

class Reply:
    def __init__(self, discordClient):
        self.client = discordClient

    async def on_message(self, message):
        if message.author == self.user:
            return

        if message.content.startswith('$hello'):
            await message.channel.send('Hello World!')
        await client.process_commands(message)
````

musicbot/bot.py
```python
import discord
import logging
import sys
from discord.ext import commands
from .cogs import music, error, meta, tips, reply
from . import config

cfg = config.load_config()
bot = commands.Bot(command_prefix=cfg["prefix"])
discordClient = discord.Client

@bot.event
async def on_ready():
    logging.info(f"Bot logado como {bot.user.name}")

COGS = [music.Music, error.CommandErrorHandler, meta.Meta, tips.Tips]

def add_cogs(bot):
    for cog in COGS:
        bot.add_cog(cog(bot, cfg))
    bot.add_cog(reply.Reply(discordClient))

def run():
    add_cogs(bot)
    if cfg["token"] == "":
        raise ValueError("Nenhum token fornecido. Por favor verifique se o arquivo config.toml contem o token do bot.")
        sys.exit(1)
    bot.run(cfg["token"])
```

And i get this error:

```bash
musicbot@persephone:~/bot$ pipenv run python3 -m musicbot
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/musicbot/bot/musicbot/__main__.py", line 18, in <module>
    bot.run()
  File "/var/musicbot/bot/musicbot/bot.py", line 24, in run
    add_cogs(bot)
  File "/var/musicbot/bot/musicbot/bot.py", line 21, in add_cogs
    bot.add_cog(reply.Reply(discordClient))
  File "/var/musicbot/.local/share/virtualenvs/bot-BNrfCbEZ/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 505, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog
```

If anyone can help.

**Comment by Motchanyy** [comment]
+1

**Comment by joek13** [comment]
Hello! Thanks for your interest in my project.

Firstly, I apologize for the delay in getting back to you. I'm a full-time student and don't always give these projects the attention they deserve. Thank you for your patience.

I created the "support" label in response to this question, since it doesn't actually identify a problem with the project. In fact, you're trying to extend the product. I encourage you to experiment, so hopefully I can help out to some degree.

I've taken your code and tweaked it slightly to make everything work. I've added comments explaining each of the changes I made to make your code work.

Here's my `musicbot/cogs/reply.py`:

```python
# import discord.py's command extension module
# see the documentation: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#
from discord.ext import commands

# made Reply subclass commands.Cog
class Reply(commands.Cog):
    # Cogs must take the Bot and a config dict as arguments,
    # based on the way I have set things up in bot.py
    def __init__(self, bot, config):
        # keep a reference to the Bot object
        self.bot = bot
        # register the on_message function as a listener for the
        # `on_message` event.
        self.bot.add_listener(self.on_message, "on_message")

    async def on_message(self, message):
        if message.author == self.bot.user:
            return

        if message.content.startswith('$hello'):
            await message.channel.send('Hello World!')

        # use self.bot instead of self.client
        await self.bot.process_commands(message)
```

And my `musicbot/bot.py`:

```python
import discord
import logging
import sys
from discord.ext import commands
# import your new reply cog
from .cogs import music, error, meta, tips, reply
from . import config

cfg = config.load_config()

bot = commands.Bot(command_prefix=cfg["prefix"])
# you can't access the Client using discord.Client.
# you need to access it using bot.client.


@bot.event
async def on_ready():
    logging.info(f"Logged in as {bot.user.name}")


# add the Reply cog to the list of cogs to be initialized.
COGS = [music.Music, error.CommandErrorHandler,
        meta.Meta, tips.Tips, reply.Reply]


def add_cogs(bot):
    for cog in COGS:
        bot.add_cog(cog(bot, cfg))  # Initialize the cog and add it to the bot


def run():
    add_cogs(bot)
    if cfg["token"] == "":
        raise ValueError(
            "Nenhum token fornecido. Por favor verifique se o arquivo config.toml contem o token do bot."
        )
        sys.exit(1)
    bot.run(cfg["token"])
```

As a final note, this is a great way to experiment and learn about `discord.py`. As a future exercise I would suggest looking at the [Command API](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#commands) from `discord.py`'s command extension module. You can see several examples of how I define commands using this API in the [Music cog](musicbot/cogs/music.py):

```python
@commands.command(aliases=["stop"])
@commands.guild_only()
@commands.has_permissions(administrator=True)
async def leave(self, ctx):
    """Leaves the voice channel, if currently in one."""
    client = ctx.guild.voice_client
    state = self.get_state(ctx.guild)
    if client and client.channel:
        await client.disconnect()
        state.playlist = []
        state.now_playing = None
    else:
        raise commands.CommandError("Not in a voice channel.")
```

This has a few advantages:
- You can avoid writing parsing logic using `startswith`. This is especially helpful if your command takes several arguments.
- You can use pre-defined [checks](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#checks) like `guild_only` to, for instance, make sure a command cannot be run in private messages.

Let me know if this works out for you! Hope you are enjoying learning with my project.

**Comment by sistematico** [comment]
> Hello! Thanks for your interest in my project.
> 
> Firstly, I apologize for the delay in getting back to you. I'm a full-time student and don't always give these projects the attention they deserve. Thank you for your patience.
> 
> I created the "support" label in response to this question, since it doesn't actually identify a problem with the project. In fact, you're trying to extend the product. I encourage you to experiment, so hopefully I can help out to some degree.
> 
> I've taken your code and tweaked it slightly to make everything work. I've added comments explaining each of the changes I made to make your code work.
> 
> Here's my `musicbot/cogs/reply.py`:
> 
> ```python
> # import discord.py's command extension module
> # see the documentation: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#
> from discord.ext import commands
> 
> # made Reply subclass commands.Cog
> class Reply(commands.Cog):
>     # Cogs must take the Bot and a config dict as arguments,
>     # based on the way I have set things up in bot.py
>     def __init__(self, bot, config):
>         # keep a reference to the Bot object
>         self.bot = bot
>         # register the on_message function as a listener for the
>         # `on_message` event.
>         self.bot.add_listener(self.on_message, "on_message")
> 
>     async def on_message(self, message):
>         if message.author == self.bot.user:
>             return
> 
>         if message.content.startswith('$hello'):
>             await message.channel.send('Hello World!')
> 
>         # use self.bot instead of self.client
>         await self.bot.process_commands(message)
> ```
> 
> And my `musicbot/bot.py`:
> 
> ```python
> import discord
> import logging
> import sys
> from discord.ext import commands
> # import your new reply cog
> from .cogs import music, error, meta, tips, reply
> from . import config
> 
> cfg = config.load_config()
> 
> bot = commands.Bot(command_prefix=cfg["prefix"])
> # you can't access the Client using discord.Client.
> # you need to access it using bot.client.
> 
> 
> @bot.event
> async def on_ready():
>     logging.info(f"Logged in as {bot.user.name}")
> 
> 
> # add the Reply cog to the list of cogs to be initialized.
> COGS = [music.Music, error.CommandErrorHandler,
>         meta.Meta, tips.Tips, reply.Reply]
> 
> 
> def add_cogs(bot):
>     for cog in COGS:
>         bot.add_cog(cog(bot, cfg))  # Initialize the cog and add it to the bot
> 
> 
> def run():
>     add_cogs(bot)
>     if cfg["token"] == "":
>         raise ValueError(
>             "Nenhum token fornecido. Por favor verifique se o arquivo config.toml contem o token do bot."
>         )
>         sys.exit(1)
>     bot.run(cfg["token"])
> ```
> 
> As a final note, this is a great way to experiment and learn about `discord.py`. As a future exercise I would suggest looking at the [Command API](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#commands) from `discord.py`'s command extension module. You can see several examples of how I define commands using this API in the [Music cog](musicbot/cogs/music.py):
> 
> ```python
> @commands.command(aliases=["stop"])
> @commands.guild_only()
> @commands.has_permissions(administrator=True)
> async def leave(self, ctx):
>     """Leaves the voice channel, if currently in one."""
>     client = ctx.guild.voice_client
>     state = self.get_state(ctx.guild)
>     if client and client.channel:
>         await client.disconnect()
>         state.playlist = []
>         state.now_playing = None
>     else:
>         raise commands.CommandError("Not in a voice channel.")
> ```
> 
> This has a few advantages:
> 
>     * You can avoid writing parsing logic using `startswith`. This is especially helpful if your command takes several arguments.
> 
>     * You can use pre-defined [checks](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#checks) like `guild_only` to, for instance, make sure a command cannot be run in private messages.
> 
> 
> Let me know if this works out for you! Hope you are enjoying learning with my project.

Joe, thank you for response.
This modifications insert a bug, look at screenshot.

![image](https://user-images.githubusercontent.com/97509/134786025-d0b37ba5-99d5-49b1-9e83-359791d076e9.png)

Thank you very much.

**Comment by sistematico** [comment]
Song reply, is duplicated.

**Comment by joek13** [comment]
Good catch. 

I can confirm that on my end, the issue is fixed by removing `await self.bot.process_commands(message)` from the end of the `on_message` handler in the `Reply` cog.

```python
# import discord.py's command extension module
# see the documentation: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#
from discord.ext import commands

# made Reply subclass commands.Cog
class Reply(commands.Cog):
    # Cogs must take the Bot and a config dict as arguments,
    # based on the way I have set things up in bot.py
    def __init__(self, bot, config):
        # keep a reference to the Bot object
        self.bot = bot
        # register the on_message function as a listener for the
        # `on_message` event.
        self.bot.add_listener(self.on_message, "on_message")

    async def on_message(self, message):
        if message.author == self.bot.user:
            return

        if message.content.startswith('$hello'):
            await message.channel.send('Hello World!')
```

It looks like making the bot process commands here actually causes a redundant processing of the same message.
