### ISSUE TITLE
RIP Bot

### ISSUE THREAD

**Issue by Technetium1** [joek13/py-music-bot#5]
https://github.com/joek13/py-music-bot/blob/master/requirements.txt#L1
`WARNING: Did not find branch or tag 'rewrite', assuming revision or ref.
  Running command git checkout -q rewrite
  error: pathspec 'rewrite' did not match any file(s) known to git.`

**Comment by Technetium1** [comment]
It seems that the rewrite branch was deleted as inferred by [this comment](https://github.com/Rapptz/discord.py/issues/2210#issuecomment-500242283). Using `git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice]` gives another error
```python
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    bot.run()
  File "/path/src/bot.py", line 27, in run
    add_cogs(bot)
  File "/path/src/bot.py", line 23, in add_cogs
    bot.add_cog(cog(bot, cfg))  # Initialize the cog and add it to the bot
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 499, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog
```

**Comment by RedstonedLife** [comment]
> It seems that the rewrite branch was deleted as inferred by [this comment](https://github.com/Rapptz/discord.py/issues/2210#issuecomment-500242283). Using `git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice]` gives another error
> 
> ```python
> Traceback (most recent call last):
>   File "main.py", line 20, in <module>
>     bot.run()
>   File "/path/src/bot.py", line 27, in run
>     add_cogs(bot)
>   File "/path/src/bot.py", line 23, in add_cogs
>     bot.add_cog(cog(bot, cfg))  # Initialize the cog and add it to the bot
>   File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 499, in add_cog
>     raise TypeError('cogs must derive from Cog')
> TypeError: cogs must derive from Cog
> ```

Following your error it takes an easy fix, really.
When you create a cog it must derive from cog.
Now instead of
```class CogName:```
Its
```class CogName(commands.Cog)```

And the rewrite branch does exist, don't forget thousands of bots use the rewrite branch cause it provides more stuff to work with.
If the re-write branch would've been deleted it would cause chaos among thousands of bot developers
