### ISSUE TITLE
Can this still be used?

### ISSUE THREAD

**Issue by richielive** [joek13/py-music-bot#7]
I have entered the TOKEN and the prefix according to what you said, but it has always reported errors, I hope to have an answer!
![註解 2020-05-24 151300](https://user-images.githubusercontent.com/51959827/82748008-14bedd80-9dd1-11ea-802f-7d0b6f556b81.png)

**Comment by BHBHD** [comment]
This can be just you have to make changes.

**Comment by RedstonedLife** [comment]
Every code can be used after years, you will need to make some changes, or if someone is willing enough they might re-code it to work better and faster.
Which is something I might do. Make it faster, efficient, and smaller in size.

But yes, with some minor changes the code can still be used. Just make sure if you get an error regarding
`cogs must derive from Cog` then I answered that error in #5 and #8 .

**Comment by RedstonedLife** [comment]
@richielive this can be used if @joek13 decides to accept pull request #6 the guy did a good job although I would still make some changes.

**Comment by joek13** [comment]
Yes! Thanks to the hard work of @RedstonedLife and @plutphil, I've managed to get this totally up to speed. Please refer to the README for updated instructions on setting up the bot. Let me know if you have any more trouble.
