### ISSUE TITLE
some error when i run main.py

### ISSUE THREAD

**Issue by Jay-Surana** [joek13/py-music-bot#8]
ster/src/main.py
Traceback (most recent call last):
  File "c:/Users/Pankaj/Desktop/py-music-bot-master/src/main.py", line 20, in <module>
    bot.run()
  File "c:\Users\Pankaj\Desktop\py-music-bot-master\src\bot.py", line 27, in run
    add_cogs(bot)
  File "c:\Users\Pankaj\Desktop\py-music-bot-master\src\bot.py", line 23, in add_cogs
    bot.add_cog(cog(bot, cfg))  # Initialize the cog and add it to the bot
  File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 506, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog
PS C:\Users\Pankaj\Desktop\py-music-bot-master>

**Comment by RedstonedLife** [comment]
> ster/src/main.py
> Traceback (most recent call last):
> File "c:/Users/Pankaj/Desktop/py-music-bot-master/src/main.py", line 20, in
> bot.run()
> File "c:\Users\Pankaj\Desktop\py-music-bot-master\src\bot.py", line 27, in run
> add_cogs(bot)
> File "c:\Users\Pankaj\Desktop\py-music-bot-master\src\bot.py", line 23, in add_cogs
> bot.add_cog(cog(bot, cfg)) # Initialize the cog and add it to the bot
> File "C:\Users\Pankaj\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 506, in add_cog
> raise TypeError('cogs must derive from Cog')
> TypeError: cogs must derive from Cog
> PS C:\Users\Pankaj\Desktop\py-music-bot-master>

I already answered it in #5 But I'll be glad to do it again.
Recently `discord.py` changed so that cogs must derive from Cog.
When making a cog you do this now
```from discord.ext import commands```
```class CogName(commands.Cog):```
instead of
```class CogName:```

I hope this helps
